### ISSUE TITLE
rewrite intro based on the architecture

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/charter#9]
To accommodate Roman's suggestion to make use of what we've learned from the architecture, I think [this](https://github.com/thomas-fossati/rats-cheatsheet#objectives-and-mechanisms) may come in handy.

Concretely, we could replace this bit:

_"Remote attestation procedures (RATS) enable relying parties to establish a level of confidence in the trustworthiness of remote system components through the creation of attestation evidence by remote system components and a processing chain towards the relying party. A relying party can then decide whether to consider a remote system component trustworthy or not."_

with something similar to the "objectives and mechanisms" I linked above.

**Comment by henkbirkholz** [comment]
resolved in #10
